(()=>{
const root=document;
const $=s=>root.querySelector(s), $$=s=>[...root.querySelectorAll(s)];
const state={part:'part1',set:0,item:0,stream:null,recorder:null,chunks:[],audioUrl:null,recognition:null,transcript:'',recording:false,auto:false};
const els={tabs:$$('.tab'),setSel:$('#setSelect'),itemSel:$('#itemSelect'),prompt:$('#prompt'),group:$('#groupName'),title:$('#setTitle'),play:$('#playBtn'),auto:$('#autoBtn'),record:$('#recordBtn'),stop:$('#stopBtn'),reveal:$('#revealBtn'),prev:$('#prevBtn'),next:$('#nextBtn'),audio:$('#responseAudio'),download:$('#downloadBtn'),status:$('#status'),transcript:$('#transcript'),similarity:$('#similarity'),metricWrap:$('#metricWrap'),voice:$('#voiceSelect'),rate:$('#rateSelect'),mode:$('#modeSelect'),well:$('#well'),improve:$('#improve'),save:$('#saveBtn'),qList:$('#qList'),support:$('#supportMsg')};
function dataSets(){return TOEFL_DATA[state.part]||[]}
function itemText(set,item){return state.part==='part1'?set.sentences[item]:set.questions[item]}
function key(){const s=dataSets()[state.set]; return `toefl:${state.part}:${s?.title||''}:${state.item}`}
function loadSaved(){try{const v=JSON.parse(localStorage.getItem(key())||'{}');els.transcript.value=v.transcript||'';els.well.value=v.well||'';els.improve.value=v.improve||'';}catch(e){}}
function save(){localStorage.setItem(key(),JSON.stringify({transcript:els.transcript.value,well:els.well.value,improve:els.improve.value,updated:new Date().toISOString()})); flash('저장했습니다.','success')}
function flash(msg,cls=''){els.status.textContent=msg;els.status.className='status '+cls}
function renderSets(){const sets=dataSets();els.setSel.innerHTML='';let lastGroup='';sets.forEach((s,i)=>{if(s.group!==lastGroup){const og=document.createElement('optgroup');og.label=s.group;els.setSel.appendChild(og);lastGroup=s.group;}const opt=document.createElement('option');opt.value=i;opt.textContent=s.title;els.setSel.lastElementChild.appendChild(opt)});state.set=Math.min(state.set,sets.length-1);els.setSel.value=state.set;renderItems()}
function renderItems(){const set=dataSets()[state.set];const arr=state.part==='part1'?set.sentences:set.questions;state.item=Math.min(state.item,arr.length-1);els.itemSel.innerHTML='';arr.forEach((x,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(state.part==='part1'?'Sentence ':'Question ')+(i+1);els.itemSel.appendChild(o)});els.itemSel.value=state.item;els.group.textContent=set.group;els.title.textContent=set.title;renderQuestionButtons(arr.length);renderPrompt();}
function renderQuestionButtons(n){els.qList.innerHTML='';for(let i=0;i<n;i++){const b=document.createElement('button');b.type='button';b.className='qbtn'+(i===state.item?' active':'');b.textContent=i+1;b.addEventListener('click',()=>{state.item=i;els.itemSel.value=i;renderPrompt()});els.qList.appendChild(b)}}
function renderPrompt(){stopAll();const set=dataSets()[state.set];const txt=itemText(set,state.item);els.prompt.textContent=txt;const hide=els.mode.value==='test';els.prompt.classList.toggle('hiddenText',hide);els.reveal.textContent=hide?'문장/문제 보기':'문장/문제 숨기기';els.metricWrap.style.display=state.part==='part1'?'block':'none';els.support.textContent=state.part==='part1'?'교재의 Listen & Repeat 문장을 듣고 그대로 반복하세요.':'교재의 Interview Question을 듣고 자연스럽게 답하세요.';els.transcript.value='';els.well.value='';els.improve.value='';els.audio.removeAttribute('src');els.audio.load();els.download.disabled=true;els.similarity.textContent='—';loadSaved();updateSimilarity();$$('.qbtn').forEach((b,i)=>b.classList.toggle('active',i===state.item));flash('준비됨');}
function currentText(){return itemText(dataSets()[state.set],state.item)}
function voices(){return speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang))}
function loadVoices(){const vs=voices();const current=els.voice.value;els.voice.innerHTML='';vs.forEach((v,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${v.name} (${v.lang})`;els.voice.appendChild(o)});if(vs.length){const preferred=vs.findIndex(v=>/US|Samantha|Google US|Microsoft.*English.*United States/i.test(v.name+' '+v.lang));els.voice.value=preferred>=0?preferred:0}else{const o=document.createElement('option');o.textContent='브라우저 기본 영어 음성';els.voice.appendChild(o)}if(current && [...els.voice.options].some(o=>o.value===current))els.voice.value=current;}
loadVoices(); speechSynthesis.onvoiceschanged=loadVoices;
function speak(autoRecord=false){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(currentText());u.lang='en-US';u.rate=parseFloat(els.rate.value)||0.92;const vs=voices();if(vs[+els.voice.value])u.voice=vs[+els.voice.value];u.onstart=()=>flash(state.part==='part1'?'문장을 듣는 중...':'질문을 듣는 중...');u.onend=async()=>{flash('오디오 종료');if(autoRecord){await beginRecording();}};u.onerror=()=>flash('음성 재생에 실패했습니다. 다른 음성을 선택해 보세요.','error');speechSynthesis.speak(u)}
async function ensureStream(){if(state.stream&&state.stream.active)return state.stream;if(!navigator.mediaDevices?.getUserMedia)throw new Error('이 브라우저에서 마이크 녹음을 지원하지 않습니다.');state.stream=await navigator.mediaDevices.getUserMedia({audio:true});return state.stream}
function makeRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const r=new SR();r.lang='en-US';r.continuous=true;r.interimResults=true;let finalText=els.transcript.value.trim();r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;if(e.results[i].isFinal){finalText+=(finalText?' ':'')+s.trim()}else interim+=s}els.transcript.value=(finalText+(interim?' '+interim:'')).trim();updateSimilarity()};r.onerror=e=>{if(e.error!=='no-speech')console.warn('speech recognition',e.error)};return r}
async function beginRecording(){if(state.recording)return;try{const stream=await ensureStream();state.chunks=[];const options=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?{mimeType:'audio/webm;codecs=opus'}:{};state.recorder=new MediaRecorder(stream,options);state.recorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.recorder.onstop=()=>{const blob=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'});if(state.audioUrl)URL.revokeObjectURL(state.audioUrl);state.audioUrl=URL.createObjectURL(blob);els.audio.src=state.audioUrl;els.download.disabled=false;els.download.onclick=()=>{const a=document.createElement('a');a.href=state.audioUrl;a.download=`TOEFL_${state.part}_${state.set+1}_${state.item+1}.webm`;a.click()};flash('녹음 완료. 재생하거나 다운로드할 수 있습니다.','success');save()};state.recorder.start(250);state.recording=true;els.record.disabled=true;els.stop.disabled=false;els.play.disabled=true;els.auto.disabled=true;els.status.innerHTML='<span class="recording">● 녹음 중...</span>';state.recognition=makeRecognition();try{state.recognition?.start()}catch(e){} }catch(e){flash('마이크를 사용할 수 없습니다. HTTPS 또는 localhost에서 열고 마이크 권한을 허용해 주세요.','error')}}
function stopRecording(){if(!state.recording)return;state.recording=false;try{state.recorder?.stop()}catch(e){};try{state.recognition?.stop()}catch(e){};els.record.disabled=false;els.stop.disabled=true;els.play.disabled=false;els.auto.disabled=false;}
function stopAll(){speechSynthesis.cancel();if(state.recording)stopRecording()}
function normalize(t){return t.toLowerCase().replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim().split(' ').filter(Boolean)}
function editDistance(a,b){const dp=Array(b.length+1).fill(0).map((_,j)=>j);for(let i=1;i<=a.length;i++){let prev=dp[0];dp[0]=i;for(let j=1;j<=b.length;j++){const tmp=dp[j];dp[j]=Math.min(dp[j]+1,dp[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp}}return dp[b.length]}
function updateSimilarity(){if(state.part!=='part1')return;const ref=normalize(currentText()),hyp=normalize(els.transcript.value);if(!hyp.length){els.similarity.textContent='—';return}const dist=editDistance(ref,hyp);const score=Math.max(0,Math.round((1-dist/Math.max(1,ref.length))*100));els.similarity.textContent=score+'%';}
function setPart(p){stopAll();state.part=p;state.set=0;state.item=0;els.tabs.forEach(b=>b.classList.toggle('active',b.dataset.part===p));$('#partTitle').textContent=p==='part1'?'Part 1 · Listen & Repeat':'Part 2 · Take an Interview';$('#partDesc').textContent=p==='part1'?'문장을 오디오로 듣고, 보지 않고 반복한 뒤 녹음과 자동 받아쓰기를 확인합니다.':'인터뷰 질문을 오디오로 듣고 답변을 녹음합니다. 지원되는 브라우저에서는 답변이 자동으로 텍스트로 입력됩니다.';renderSets()}
els.tabs.forEach(b=>b.addEventListener('click',()=>setPart(b.dataset.part)));els.setSel.addEventListener('change',()=>{state.set=+els.setSel.value;state.item=0;renderItems()});els.itemSel.addEventListener('change',()=>{state.item=+els.itemSel.value;renderPrompt()});els.mode.addEventListener('change',renderPrompt);els.play.addEventListener('click',()=>speak(false));els.auto.addEventListener('click',async()=>{try{await ensureStream();speak(true)}catch(e){flash('먼저 마이크 권한을 허용해 주세요.','error')}});els.record.addEventListener('click',beginRecording);els.stop.addEventListener('click',stopRecording);els.reveal.addEventListener('click',()=>{const now=els.prompt.classList.toggle('hiddenText');els.reveal.textContent=now?'문장/문제 보기':'문장/문제 숨기기'});els.prev.addEventListener('click',()=>{if(state.item>0){state.item--;els.itemSel.value=state.item;renderPrompt()}});els.next.addEventListener('click',()=>{const s=dataSets()[state.set],n=(state.part==='part1'?s.sentences:s.questions).length;if(state.item<n-1){state.item++;els.itemSel.value=state.item;renderPrompt()}else if(state.set<dataSets().length-1){state.set++;state.item=0;els.setSel.value=state.set;renderItems()}});els.transcript.addEventListener('input',updateSimilarity);els.save.addEventListener('click',save);window.addEventListener('beforeunload',()=>{try{state.stream?.getTracks().forEach(t=>t.stop())}catch(e){}});setPart('part1');
})();