window.TOEFL_DATA.part2.push(...[
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 1","questions":["Do you prefer studying alone or with other students?","What is one thing you do to stay organized?","Tell me about a useful class you have taken.","What would you recommend to a new university student?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 2","questions":["Would you rather live on campus or off campus?","What is one good way to improve English speaking?","Tell me about a time when you worked well with a group.","Do you think students should have part-time jobs?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 3","questions":["Do you prefer online learning or in-person learning?","What do you usually do when you feel stressed?","Tell me about a goal you achieved.","What would you do if you missed an important class?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 4","questions":["Would you rather study in a library or at home?","What is one habit that helps people stay healthy?","Tell me about a teacher who influenced you.","Why is time management important?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 5","questions":["Do you prefer working on one task at a time or several tasks?","What is one campus activity you would recommend?","Tell me about a time when you had to make a difficult decision.","Do you think universities should require internships?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 6","questions":["Would you rather travel with friends or alone?","What do you usually do before an important exam?","Tell me about a useful piece of advice you received.","What would you do if your group project was behind schedule?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 7","questions":["Do you prefer reading printed books or digital books?","What is one useful technology for students?","Tell me about an experience that taught you something important.","Why do students join clubs or organizations?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 8","questions":["Would you rather take morning classes or evening classes?","What is one good way to make new friends?","Tell me about a time when you solved a problem successfully.","Do you think students should exercise regularly?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 9","questions":["Do you prefer planning ahead or being spontaneous?","What do you usually do when you do not understand something in class?","Tell me about a place where you can concentrate well.","What would you recommend to someone who wants to reduce stress?"]},
{"group":"Chapter 11 · Timed Interview","title":"Practice Set 10","questions":["Would you rather work for a large company or a small company?","What is one skill you want to improve?","Tell me about a time when you helped someone.","Do you think social media is more helpful or distracting for students?"]}]);